name: Build .NET Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: .NET Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Project Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test
