name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet publish -c Release -o build

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/**

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
